bcvideopresentation/VideoPresentation/Entities/Video.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace VideoPresentation.Entities
{
    public class Video
    {
        public Video()
        {

        }
        public Video(string videoTitle, int coAuthId ,string videoName, int authId, string videoCommentCs, string videoCommentEn, string authorCommentCs, string authorCommentEn, int year, int additionalYear, string series, string prequelCs, string prequelEn, string citationCs, string citationEn, string artisticMedium, string technicalMedium, string performerCs, string performerEs, string toolName, string toolAuthor, string toolInfo, string annottationCs, string annottationEn, string annottationReferenceCs, string annottationReferenceEn, string sourcesCs, string sourcesEn, string muniSource, int videoLength, int additionalVideoLength,string additonalAuthor)
        {
            this.VideoTitle = videoTitle;

            this.VideoName = videoName;
            this.AuthId = authId;
            this.VideoCommentCs = videoCommentCs;
            this.VideoCommentEn = videoCommentEn;
            this.AuthorCommentCs = authorCommentCs;
            this.AuthorCommentEn = authorCommentEn;
            this.Year = year;
            this.AdditionalYear = additionalYear;
            this.Series = series;
            this.PrequelCs = prequelCs;
            this.PrequelEn = prequelEn;
            this.CitationCs = citationCs;
            this.CitationEn = citationEn;
            this.ArtisticMedium = artisticMedium;
            this.TechnicalMedium = technicalMedium;
            this.PerformerCs = performerCs;
            this.PerformerEn = performerEs;
            this.VoicePerformerCs = videoCommentCs;
            this.VoicePerformerEn = videoCommentEn;
            this.ToolName = toolName;
            this.ToolAuthor = toolAuthor;
            this.ToolInfo = toolInfo;
            this.AnnotationCs = annottationCs;
            this.AnnotationEn = annottationEn;
            this.AnnotationReferenceCs = annottationReferenceCs;
            this.AnnotationReferenceEn = annottationReferenceEn;
            this.SourcesCs = sourcesCs;
            this.SourcesEn = sourcesEn;
            this.MuniSource = muniSource;
            this.VideoLength = videoLength;
            this.AdditionalVideoLength = additionalVideoLength;
            this.CoAuthId = coAuthId;
            this.AdditonalAuthor = additonalAuthor;
        }

        

        public int ID { get; set; }
        public string VideoTitle { get; set; }
        public string VideoName { get; set; }
        public int AuthId { get; set; }
        public int CoAuthId { get; set; }
        public string VideoCommentCs { get; set; }
        public string VideoCommentEn { get; set; }
        public string AuthorCommentCs { get; set; }
        public string AuthorCommentEn { get; set; }
        public int Year { get; set; }
        public int AdditionalYear { get; set; }
        public string Series { get; set; }
        public string PrequelCs { get; set; }
        public string PrequelEn { get; set; }
        public string CitationCs { get; set; }
        public string CitationEn { get; set; }
        public string ArtisticMedium { get; set; }
        public string TechnicalMedium { get; set; }
        public string PerformerCs { get; set; }
        public string PerformerEn { get; set; }
        public string VoicePerformerCs { get; set; }
        public string VoicePerformerEn { get; set; }
        public string ToolName { get; set; }
        public string ToolAuthor { get; set; }
        public string ToolInfo { get; set; }
        public string AnnotationCs { get; set; }
        public string AnnotationEn { get; set; }
        public string AnnotationReferenceCs { get; set; }
        public string AnnotationReferenceEn { get; set; }
        public string SourcesCs { get; set; }
        public string SourcesEn { get; set; }
        public string MuniSource { get; set; }
        public int VideoLength { get; set; }
        public int AdditionalVideoLength { get; set; }
        public string AdditonalAuthor { get; set; }
    }
}

bcvideopresentation/VideoPresentation/Controllers/CultureController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using System.Threading.Tasks;

namespace VideoPresentation.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
               CookieRequestCultureProvider.DefaultCookieName,
               CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
               new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
           );
            return LocalRedirect(returnUrl);
        }

    }
}

bcvideopresentation/VideoPresentation/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VideoPresentation.Models;
using MySql.Data.MySqlClient;
using System.Data;
using VideoPresentation.Connection;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using VideoPresentation.Entities;
using VideoPresentation.Infrastructure.Database.VideoTags;
using System.Web.Helpers;

namespace VideoPresentation.Controllers
{

    public class VideoController : Controller
    {
        private Infrastructure.Database.IVideosRepository videosRepository;
        private Infrastructure.Database.IAuthorsRepository authorsRepositroy;
        public VideoController(Infrastructure.Database.IVideosRepository videoRepository, Infrastructure.Database.IAuthorsRepository authorRepositroy)
        {
            this.videosRepository = videoRepository;
            this.authorsRepositroy = authorRepositroy;       
        }

        [HttpPost]
        public IActionResult DeleteVideo(Video video)
        {
            videosRepository.RemoveVideo(video);

            return RedirectToAction("DbView");
        }
        public IActionResult DeleteVideo(int id)
        {
            Video v = videosRepository.GetVideoById(id);
            return View(v);
        }
        public IActionResult SearchResults(string fileName)
        {
            List<Video> videolist = videosRepository.SearchVideo(fileName);
            return View(videolist);
        }
        public IActionResult TagsResults(int tagID)
        {
            List<Video> videolist = videosRepository.GetVideosWithTag(tagID);
            List<UploadModel> umList = new List<UploadModel>();
            List<Author> authList = authorsRepositroy.GetAllAuthors();
            foreach (Video v in videolist)
            {
                UploadModel um = new UploadModel(v, authList);
                um.TagWeights = videosRepository.GetTagWeightsForVideo(v.ID);
                umList.Add(um);
            }

            return View(umList);
        }

        public IActionResult DbView()
        {
            List<Video> videolist = videosRepository.GetAllVideos();
            List<UploadModel> umList = new List<UploadModel>();
            List<Author> authList = authorsRepositroy.GetAllAuthors();
            foreach (Video v in videolist)
            {
                UploadModel um = new UploadModel(v, authList);
                um.TagWeights = videosRepository.GetTagWeightsForVideo(v.ID);
                umList.Add(um);
            }

            return View(umList);
        }
        public IActionResult GetJsonTags(int id)
        {
            List<TagPosition> taglist = videosRepository.GetJsonTagById(id);
            return new JsonResult(taglist);
        }


        public IActionResult Play(int id)
        {
            Video v = videosRepository.GetVideoById(id);
            List<Author> authorsList = authorsRepositroy.GetAllAuthors();
            Author autor = authorsRepositroy.GetAuthorById(v.AuthId);
            UploadModel um = new UploadModel(v, autor);

            UploadModel um2 = new UploadModel(v, authorsRepositroy.GetAllAuthors());

            return View(um2);
        }
        [Authorize(Roles = "Admin, User")]
        public IActionResult Edit(int id)
        {
            new UploadModel();
            Video v = videosRepository.GetVideoById(id);
            Author author = authorsRepositroy.GetAuthorById(v.AuthId);
            UploadModel um = new UploadModel(v, authorsRepositroy.GetAllAuthors());
            return View(um);
        }
       
        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        public IActionResult Edit(UploadModel videoModel)
        {           
            videosRepository.EditVideo(videoModel.CreateVideo());
            return Redirect("DbView");
        }
    }

}

bcvideopresentation/VideoPresentation/Views/Shared/About_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
@{
    ViewData["Title"] = "About_Layout";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">

        <b>
            <nav class="menu1">
                <ul>
                    <li><a href="Introduction">@localizer["Introduction"]</a></li>                   
                    <li><a href="Live_archive">@localizer["LiveArchive"]</a></li>
                    <li><a href="IntelligentAtlas">@localizer["IntelligentAtlas"]</a></li>
                    <li><a href="dataset">Dataset</a></li>
                    <li><a href="findings">@localizer["Findings"]</a></li>
                    <li><a href="theory">@localizer["Theory"]</a></li>

                </ul>
            </nav>
        </b>
    </div>



    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>

bcvideopresentation/VideoPresentation/Views/Shared/Credits_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
@{
    ViewData["Title"] = "Credits_Layout";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">


        <b>
            <nav class="menu1">
                <ul>
                    <li><a href="team_members">@localizer["Team members"]</a></li>
                    <li><a href="application_guarants">@localizer["Application guarants"]</a></li>
                    <li><a href="contact">@localizer["Contact"]</a></li>

                </ul>
            </nav>
        </b>

    </div>


    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>

bcvideopresentation/VideoPresentation/Views/Shared/Culture_Partial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions


@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures.Select(c => new SelectListItem { Value = c.Name, Text = Localizer.GetString(c.Name) }).ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage"
          asp-controller="Culture"
          asp-action="SetCulture"
          asp-route-returnUrl="@returnUrl"
          method="post"
          class="form-horizontal nav-link text-dark"
          role="form">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>

bcvideopresentation/VideoPresentation/Views/Shared/Home_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">





    <div style="width:100%;text-align:center">

        <p>
            <span class="lg1">
                VASULKA LIVE ARCHIVE
                <!--Vasulka Live Archive-->
            </span>

        </p>
    </div>

    <b>
        <nav class="search-menu">
            <ul>
                <li>
                    @using (Html.BeginForm("SearchResults", "Video", FormMethod.Get))
                    {
                        @Html.TextBox("fileName", null, new { @class = "search-input" })
                        <input class="find-button find-button-action" type="submit" value="@localizer["Search"]" />
                    }
                </li>
                <li class="combobox">@await Html.PartialAsync("Culture_Partial", new { @class = "search-input" })</li>
                <li>

                    @if (User.IsInRole("Admin"))
                    {

                        <a style="font-size:15px" href="/login/login">
                            @localizer["Welcome"]: @User.Identity.Name
                        </a>
                        <a style="font-size:15px;" , asp-action="logout" asp-controller="Login">
                            @localizer["Logout"]
                        </a>
                    }
                    else
                    {
                    <li><a style="font-size:15px;" href="/login/login">@localizer["Log in"]</a></li>
                }
                    </li>

                </ul>
            </nav>
            <div class="menu">
                <ul>
                    <li><a href="/home/index">@localizer["Home"]</a></li>
                    <li><a href="/Video/DbView">@localizer["LiveArchive"]</a></li>
                    <li><a href="/MachineVision/MachineVision">@localizer["IntelligentAtlas"]</a></li>
                    <li><a href="/home/software">@localizer["Software"]</a></li>
                    <li><a href="/about/introduction">@localizer["About"]</a></li>
                    <li><a href="/credits/team_members">@localizer["Credits"]</a></li>
                </ul>
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>

            </div>

        </b>









        <div id="content">
            @RenderBody()
        </div>

        <div style="clear:both; height: 2em;"> </div>

        <script>
            const hamburger = document.querySelector(".hamburger");
            const navMenu = document.querySelector(".menu ul");

            const lg1 = document.querySelector(".lg1");
            hamburger.addEventListener("click", mobileMenu);

            function mobileMenu() {
                hamburger.classList.toggle("active");
                navMenu.classList.toggle("active");
                lg1.classList.toggle("active");
            }
            const navLink = document.querySelectorAll(".menu ul li a");

            navLink.forEach(n => n.addEventListener("click", closeMenu));

            function closeMenu() {

                lg1.classList.toggle("active");
                hamburger.classList.remove("active");
                navMenu.classList.remove("active");
            }
        </script>


        @RenderSection("Scripts", required: false)
    </body>
</html>

bcvideopresentation/VideoPresentation/Views/Shared/LoginLayout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
@{
    ViewData["Title"] = "LoginLayout";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>        


    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">

        @if (User.IsInRole("Admin"))
        {


            <b>
                <nav class="menu1">
                    <ul>
                        <li><a href="addUser">@localizer["AddUser"]</a></li>
                        <li><a href="AllUsers">@localizer["ShowAllUsers"]</a></li>
                        <li><a href="AddAuthor">@localizer["AddAuthor"]</a></li>
                        <li><a href="AllAuthors">@localizer["ShowAllAuthors"]</a></li>
                        <li><a href="/upload/upload">@localizer["UploadVideo"]</a></li>

                    </ul>
                </nav>
            </b>
        }

    </div>


    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>

bcvideopresentation/VideoPresentation/Views/Shared/Machine_Learning_Layout.cshtml
<!DOCTYPE html>
@{
    ViewData["Title"] = "Credits_Layout";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">


        <b>
            <nav class="menu1">
                <ul>
                    <li><a href="team_members">Team members</a></li>
                    <li><a href="application_guarants">Application guarants</a></li>
                    <li><a href="contact">Press, contact, social media</a></li>

                </ul>
            </nav>
        </b>

    </div>


    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>

bcvideopresentation/VideoPresentation/Views/Shared/UploadLayout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
@{
    ViewData["Title"] = "UploadLayout";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>        


    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">

        @if (User.IsInRole("Admin"))
        {


            <b>
                <nav class="menu1">
                    <ul>
                        <li><a href="/login/addUser">@localizer["AddUser"]</a></li>
                        <li><a href="/login/AllUsers">@localizer["ShowAllUsers"]</a></li>
                        <li><a href="/login/AddAuthor">@localizer["AddAuthor"]</a></li>
                        <li><a href="/login/AllAuthors">@localizer["ShowAllAuthors"]</a></li>
                        <li><a href="upload">@localizer["UploadVideo"]</a></li>

                    </ul>
                </nav>
            </b>
        }

    </div>


    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>

bcvideopresentation/VideoPresentation/Views/Shared/Video.cshtml
<!DOCTYPE html>
@{
    ViewData["Title"] = "Video";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoPresentation</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="css-selectorbg">

    <div style="width:100%;text-align:center">


      

    </div>


    <div id="content">
        @RenderBody()
    </div>

    <div style="clear:both; height: 2em;"> </div>

</body>
@RenderSection("Scripts", required: false)
</html>